version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5433
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=sales_dashboard
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start

volumes:
  postgres_data:
